name: Build Cordova App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova project
        run: cordova create myApp com.niced.firstapp "Kichu Pottan"

      - name: Copy config.xml
        run: cp config.xml myApp/config.xml

      - name: Copy icon.png
        run: cp icon.png myApp/icon.png

      - name: Add Android platform
        run: |
          cd myApp
          cordova platform add android

      - name: Build Cordova project
        run: |
          cd myApp
          cordova build android --release -- --packageType=bundle

      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '14'

      - name: Download Bundletool
        run: |
          wget -O bundletool.jar https://github.com/google/bundletool/releases/download/1.15.1/bundletool-all-1.15.1.jar

      - name: Generate APK
        run: |
          cd myApp
          java -jar ../bundletool.jar build-apks --bundle=platforms/android/app/build/outputs/bundle/release/app-release.aab --output=app-release.apks --mode=universal

      - name: Extract APK from APK Set
        run: |
          unzip -j myApp/app-release.apks 'universal.apk' -d apk

      - name: Move APK to 'apk' directory
        run: |
          mv apk/universal.apk apk/app-release.apk

      - name: Create APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: APK
          path: apk/app-release.apk
