name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Cordova
        run: npm install -g cordova

      - name: Build APK
        run: |
          # Create a new Cordova project
          cordova create myApp
          cd myApp

          # Add the Android platform
          cordova platform add android

          # Copy the index.html file to the www directory
          cp ${{ github.workspace }}/index.html www/index.html

          # Build the Android project in release mode
          cordova build android --release

          # Create the 'apk' directory if it doesn't exist
          mkdir -p ${{ github.workspace }}/apk

          # Move the generated APK file to the 'apk' directory
          mv platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk ${{ github.workspace }}/apk/app-release-unsigned.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: myApp-APK
          path: ${{ github.workspace }}/apk/app-release-unsigned.apk
