name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Cordova
        run: npm install -g cordova

      - name: Build AAB
        run: |
          cd MyApp
          cordova platform add android
          cordova build android --release -- -- --packageType=bundle

      - name: Convert AAB to APK
        run: |
          cd MyApp/platforms/android/app/build/outputs/bundle/release/
          bundletool build-apks --bundle=app-release.aab --output=app.apks --mode=universal

      - name: Extract APK from AAB
        run: |
          cd MyApp/platforms/android/app/build/outputs/bundle/release/
          unzip -o app.apks

      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: MyApp-APK
          path: MyApp/platforms/android/app/build/outputs/bundle/release/splits/*.apk
