name: PhoneGap Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install PhoneGap CLI
        run: npm install -g phonegap-cli

      - name: Generate config.xml
        run: |
          echo '<widget id="com.niced.firstapp" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">' > config.xml
          echo '  <name>Kichu Pottan</name>' >> config.xml
          echo '  <description>A simple PhoneGap app</description>' >> config.xml
          echo '  <author email="author@example.com" href="https://www.example.com">Author Name</author>' >> config.xml
          echo '</widget>' >> config.xml

      - name: Change directory to myApp
        run: cd myApp

      - name: Build PhoneGap app
        run: phonegap build

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: phonegap-artifacts
          path: myApp/platforms/android/app/build/outputs

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: myApp/platforms/android/app/build/outputs/apk/release/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: myApp/platforms/android/app/build/outputs/bundle/release/app-release.aab
