name: Create APK from HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java 8
  uses: actions/setup-java@v2
  with:
    java-version: 8
    architecture: x64

      - name: Download and unzip Android SDK
        run: |
          wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O android-sdk.zip
          mkdir android-sdk
          unzip -q android-sdk.zip -d android-sdk

      - name: Accept Android licenses
        run: yes | android-sdk/tools/bin/sdkmanager --licenses

      - name: Set Android SDK environment variables
        run: |
          echo "export ANDROID_HOME=$(pwd)/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$PATH:$(pwd)/android-sdk/platform-tools:$(pwd)/android-sdk/tools:$(pwd)/android-sdk/tools/bin" >> $GITHUB_ENV

      - name: Install Android Build Tools and Platform Tools
        run: |
          android-sdk/tools/bin/sdkmanager "build-tools;30.0.3" "platform-tools"

      - name: Build APK
        run: |
          npm install -g androidjs-cli
          androidjs create myApp
          cd myApp
          cp ${{ github.workspace }}/index.html app/index.html
          # Build the APK
          androidjs build android

      - name: Move APK to 'apk' directory
        run: |
          mkdir -p ${{ github.workspace }}/apk
          mv ${{ github.workspace }}/myApp/platforms/android/app/build/outputs/apk/debug/app-debug.apk ${{ github.workspace }}/apk/app-debug.apk

      - name: Create APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: APK
          path: ${{ github.workspace }}/apk
