name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install OpenJDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Download bundletool
        run: |
          curl -O https://github.com/google/bundletool/releases/download/1.7.0/bundletool-all-1.7.0.jar
          mv bundletool-all-1.7.0.jar bundletool.jar

      - name: Build AAB
        run: |
          cordova platform add android
          cordova build android --release -- -- --packageType=bundle

      - name: Convert AAB to APK
        run: |
          cd platforms/android/app/build/outputs/bundle/release/
          java -jar ../../../bundletool.jar build-apks --bundle=app-release.aab --output=app.apks --mode=universal

      - name: Extract APK from AAB
        run: |
          cd platforms/android/app/build/outputs/bundle/release/
          unzip -o app.apks

      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: MyApp-APK
          path: platforms/android/app/build/outputs/bundle/release/splits/*.apk
