name: HTML to APK Conversion

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Cordova
        run: npm install -g cordova

      - name: Build AAB
        run: |
          cordova create myApp
          cd myApp
          cordova platform add android
          cp ${{ github.workspace }}/index.html www/index.html
          cordova build android --release -- --packageType=bundle

          # Create the 'aab' directory if it doesn't exist
          mkdir -p ${{ github.workspace }}/aab

          # Move the generated AAB file to the 'aab' directory
          mv platforms/android/app/build/outputs/bundle/release/app-release.aab ${{ github.workspace }}/aab/app-release.aab

      - name: Create AAB artifact
        uses: actions/upload-artifact@v2
        with:
          name: AAB
          path: ${{ github.workspace }}/aab
